-- Create a table to track daily ad watches
CREATE TABLE public.daily_ad_watches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id),
    watch_date DATE NOT NULL DEFAULT CURRENT_DATE,
    watch_count INT NOT NULL DEFAULT 1,
    UNIQUE (user_id, watch_date)
);

-- Create a function to get the daily ad watch count for a user
CREATE OR REPLACE FUNCTION public.get_daily_ad_watch_count(p_user_id UUID)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    watch_count INT;
BEGIN
    SELECT COALESCE(SUM(watch_count), 0)
    INTO watch_count
    FROM public.daily_ad_watches
    WHERE user_id = p_user_id AND watch_date = CURRENT_DATE;

    RETURN watch_count;
END;
$$;

-- Create a function to increment the daily ad watch count
CREATE OR REPLACE FUNCTION public.increment_daily_ad_watch_count()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NEW.description = 'Watched rewarded video ad' THEN
        INSERT INTO public.daily_ad_watches (user_id, watch_date, watch_count)
        VALUES (NEW.user_id, CURRENT_DATE, 1)
        ON CONFLICT (user_id, watch_date)
        DO UPDATE SET watch_count = daily_ad_watches.watch_count + 1;
    END IF;

    RETURN NEW;
END;
$$;

-- Create a trigger to automatically increment the daily ad watch count
CREATE TRIGGER increment_daily_ad_watch_count_trigger
AFTER INSERT ON public.transactions
FOR EACH ROW
EXECUTE FUNCTION public.increment_daily_ad_watch_count();
